export const MOVIES_DB = {
    "1": { _id: "1", title: "La La Land", year: 2016, genre: ["Romance", "Musical"], mood: ["Romance"], rating: 7.9, description: "A jazz musician and an aspiring actress fall in love while chasing their Hollywood dreams. A stunning bittersweet modern romance about sacrifice, passion, and the cost of ambition.", posterUrl: "https://image.tmdb.org/t/p/w780/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", bgUrl: "https://image.tmdb.org/t/p/original/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", posterColor: "linear-gradient(135deg,#2C0A40,#C860A8)", neon: "#E879F9", cast: [{ name: "Ryan Gosling", img: "https://image.tmdb.org/t/p/w185/0Y0XiCTwXLGJOVasGVKiggYbp.jpg" }, { name: "Emma Stone", img: "https://image.tmdb.org/t/p/w185/p4UiyoMXomrafE91dxp5a9IYXS.jpg" }, { name: "John Legend", img: "https://image.tmdb.org/t/p/w185/kMTcBuBHaT9UFjF3nBpzpVVj.jpg" }], trailerLink: "https://www.youtube.com/watch?v=0pdqf4P9MB8" },
    "2": { _id: "2", title: "Interstellar", year: 2014, genre: ["Sci-Fi", "Drama"], mood: ["Sci-Fi", "Emotional"], rating: 8.6, description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival. Earth's future has been riddled by disasters and humanity is slowly ending.", posterUrl: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", bgUrl: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg", posterColor: "linear-gradient(135deg,#050A18,#3A88D8)", neon: "#38BDF8", cast: [{ name: "Matthew McConaughey", img: "https://image.tmdb.org/t/p/w185/yVGCQzDhyxABBHhkgTEPbAHT3uQ.jpg" }, { name: "Anne Hathaway", img: "https://image.tmdb.org/t/p/w185/tLelKoPNiyAlnSgYVNjeRtJQsTP.jpg" }, { name: "Jessica Chastain", img: "https://image.tmdb.org/t/p/w185/y5SFQ6ufOHOX60NmwJBpjWXRnkJ.jpg" }], trailerLink: "https://www.youtube.com/watch?v=zSWdZVtXT7E" },
    "3": { _id: "3", title: "The Lion King", year: 1994, genre: ["Animation", "Drama"], mood: ["Emotional", "Happy"], rating: 8.5, description: "A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and courage. A timeless classic beloved by generations.", posterUrl: "https://image.tmdb.org/t/p/w780/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", bgUrl: "https://image.tmdb.org/t/p/original/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", posterColor: "linear-gradient(135deg,#0A2A14,#28C898)", neon: "#34D399", cast: [{ name: "Matthew Broderick", img: "https://image.tmdb.org/t/p/w185/2Latza1HUMbEWlHe3YUeGfqGePP.jpg" }, { name: "Jeremy Irons", img: "https://image.tmdb.org/t/p/w185/4EvFP0VXE9SHYO8PaUyLMg7wMMI.jpg" }, { name: "James Earl Jones", img: "https://image.tmdb.org/t/p/w185/qMOAJYXJTIRHzRuEGYmUJ0EHFco.jpg" }], trailerLink: "https://www.youtube.com/watch?v=4sj1MT05lAA" },
    "4": { _id: "4", title: "Breaking Bad", year: 2008, genre: ["Thriller", "Drama"], mood: ["Thriller"], rating: 9.5, description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future. The greatest TV show ever made.", posterUrl: "https://image.tmdb.org/t/p/w780/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", bgUrl: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", posterColor: "linear-gradient(135deg,#1A0808,#D85030)", neon: "#FB923C", cast: [{ name: "Bryan Cranston", img: "https://image.tmdb.org/t/p/w185/7Jahy5LZX2Fo8fGJltMreAI49hC.jpg" }, { name: "Aaron Paul", img: "https://image.tmdb.org/t/p/w185/u6Rb3qPMuiPhGsCnMiEJoTBTxhR.jpg" }, { name: "Anna Gunn", img: "https://image.tmdb.org/t/p/w185/adppyeu95gNiMuxHOOf9VKOoREy.jpg" }], trailerLink: "https://www.youtube.com/watch?v=HhesaQXLuRY" },
    "5": { _id: "5", title: "Oppenheimer", year: 2023, genre: ["Biography", "Drama"], mood: ["Emotional", "Motivated"], rating: 8.9, description: "The story of J. Robert Oppenheimer and the development of the atomic bomb during World War II. A haunting portrait of genius, guilt, and the weight of world-changing decisions.", posterUrl: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", bgUrl: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg", posterColor: "linear-gradient(135deg,#1a0808,#8B2500)", neon: "#F97316", cast: [{ name: "Cillian Murphy", img: "https://image.tmdb.org/t/p/w185/dm6V24NjjvjMiCtbMkc8Y2WPm2.jpg" }, { name: "Emily Blunt", img: "https://image.tmdb.org/t/p/w185/oizMQUF3K9OdVNBZTFb8bXp4UcP.jpg" }, { name: "Robert Downey Jr.", img: "https://image.tmdb.org/t/p/w185/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg" }], trailerLink: "https://www.youtube.com/watch?v=uYPbbksJxIg" },
    "6": { _id: "6", title: "Avatar 2", year: 2022, genre: ["Sci-Fi", "Adventure"], mood: ["Sci-Fi"], rating: 7.6, description: "Jake Sully lives with his newfound family on Pandora and faces a familiar threat that forces him to protect his home and the people he loves at all costs.", posterUrl: "https://image.tmdb.org/t/p/w780/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg", bgUrl: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwpapmrhgqpaAjAS.jpg", posterColor: "linear-gradient(135deg,#04122A,#1B5FA3)", neon: "#38BDF8", cast: [{ name: "Sam Worthington", img: "https://image.tmdb.org/t/p/w185/7AhDRRzwVDQfFqmNdFnfuMjSbHH.jpg" }, { name: "Zoe Saldana", img: "https://image.tmdb.org/t/p/w185/iOVIbAYTBQLpqKOeSfvnSzjrPuy.jpg" }, { name: "Sigourney Weaver", img: "https://image.tmdb.org/t/p/w185/nlDHSRCspaJoYcQnO2hQGBBq5Yh.jpg" }], trailerLink: "https://www.youtube.com/watch?v=d9MyW72ELq0" },
    "7": { _id: "7", title: "The Notebook", year: 2004, genre: ["Romance", "Drama"], mood: ["Romance", "Emotional"], rating: 7.8, description: "A poor yet passionate young man falls in love with a rich girl, separated by her disapproving family. Decades later their love story is retold from a notebook.", posterUrl: "https://image.tmdb.org/t/p/w780/qom1SZSENdmHFNZBXbtLAGselSo.jpg", bgUrl: "https://image.tmdb.org/t/p/original/qom1SZSENdmHFNZBXbtLAGselSo.jpg", posterColor: "linear-gradient(135deg,#3A0A20,#D45080)", neon: "#E879F9", cast: [{ name: "Ryan Gosling", img: "https://image.tmdb.org/t/p/w185/0Y0XiCTwXLGJOVasGVKiggYbp.jpg" }, { name: "Rachel McAdams", img: "https://image.tmdb.org/t/p/w185/4hhFkBWfOtMbUTvHDdbvYOifFN8.jpg" }, { name: "James Garner", img: "https://image.tmdb.org/t/p/w185/8H5DfBXORkDQl2lWCiWGHEVEKZz.jpg" }], trailerLink: "https://www.youtube.com/watch?v=k9KsmQZdMxk" },
    "8": { _id: "8", title: "Inception", year: 2010, genre: ["Sci-Fi", "Thriller"], mood: ["Sci-Fi", "Thriller"], rating: 8.8, description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO. Reality bends at every turn.", posterUrl: "https://image.tmdb.org/t/p/w780/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", bgUrl: "https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", posterColor: "linear-gradient(135deg,#0A0A2A,#4040C8)", neon: "#818CF8", cast: [{ name: "Leonardo DiCaprio", img: "https://image.tmdb.org/t/p/w185/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg" }, { name: "Joseph Gordon-Levitt", img: "https://image.tmdb.org/t/p/w185/z9hiCTuHGDUZ8XGMhMFGOxNWBzH.jpg" }, { name: "Ellen Page", img: "https://image.tmdb.org/t/p/w185/9HBjSCPfJ9zRJcE5yhO5U2GHqMD.jpg" }], trailerLink: "https://www.youtube.com/watch?v=YoHD9XEInc0" },
    "9": { _id: "9", title: "The Dark Knight", year: 2008, genre: ["Action", "Thriller"], mood: ["Thriller", "Motivated"], rating: 9.0, description: "Batman faces the Joker, a criminal mastermind determined to plunge Gotham City into chaos and anarchy. A cinematic landmark that redefined the superhero genre.", posterUrl: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg", bgUrl: "https://image.tmdb.org/t/p/original/nMKdUFyrkinsqBr2nIt6n5zi7BU.jpg", posterColor: "linear-gradient(135deg,#050510,#303080)", neon: "#818CF8", cast: [{ name: "Christian Bale", img: "https://image.tmdb.org/t/p/w185/qCpZn2e3dimwbryLnqxZuI88PTi.jpg" }, { name: "Heath Ledger", img: "https://image.tmdb.org/t/p/w185/5Y9HnYYa9jF4NunY9pt1EQBxlQ6.jpg" }, { name: "Aaron Eckhart", img: "https://image.tmdb.org/t/p/w185/qMu73QcWQJENeqQdPkpxApGeJ0J.jpg" }], trailerLink: "https://www.youtube.com/watch?v=EXeTwQWrcwY" },
    "10": { _id: "10", title: "Coco", year: 2017, genre: ["Animation", "Drama"], mood: ["Happy", "Emotional"], rating: 8.4, description: "A young boy travels to the Land of the Dead to find his great-great-grandfather and pursue his passion for music. Pixar's most emotional masterpiece.", posterUrl: "https://image.tmdb.org/t/p/w780/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg", bgUrl: "https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg", posterColor: "linear-gradient(135deg,#3A0A40,#C84040)", neon: "#FB923C", cast: [{ name: "Anthony Gonzalez", img: "https://image.tmdb.org/t/p/w185/iGMWQ1kzSpRMGODLkL1EYGejHMY.jpg" }, { name: "Gael García Bernal", img: "https://image.tmdb.org/t/p/w185/xlRk3vBGp8graCTbxPaRMsVFHoY.jpg" }, { name: "Benjamin Bratt", img: "https://image.tmdb.org/t/p/w185/2cFyfBRSSgRBzlXJyxKBEGa5Sxu.jpg" }], trailerLink: "https://www.youtube.com/watch?v=Ga6RYejo6Hk" },
    "11": { _id: "11", title: "Parasite", year: 2019, genre: ["Thriller", "Drama"], mood: ["Thriller"], rating: 8.5, description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Parks and the destitute Kims in modern Seoul.", posterUrl: "https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", bgUrl: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", posterColor: "linear-gradient(135deg,#0A1A10,#204820)", neon: "#34D399", cast: [{ name: "Song Kang-ho", img: "https://image.tmdb.org/t/p/w185/oHcSPTUxFqclFYgxv7HHjDtqd7Y.jpg" }, { name: "Lee Sun-kyun", img: "https://image.tmdb.org/t/p/w185/iGaIEXe4QwEjKyVQNNsS2X0RWyb.jpg" }, { name: "Cho Yeo-jeong", img: "https://image.tmdb.org/t/p/w185/fYGHNtSMGeFiPXQPMw9OacZ0jTR.jpg" }], trailerLink: "https://www.youtube.com/watch?v=5xH0HfJHsaY" },
    "12": { _id: "12", title: "Forrest Gump", year: 1994, genre: ["Drama", "Romance"], mood: ["Emotional", "Happy"], rating: 8.8, description: "The presidencies of Kennedy and Johnson, the Vietnam War, Watergate, and other historical events unfold through the perspective of an Alabama man with a low IQ. A beautiful story about destiny and love.", posterUrl: "https://image.tmdb.org/t/p/w780/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", bgUrl: "https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg", posterColor: "linear-gradient(135deg,#0A1A28,#2A5A8A)", neon: "#38BDF8", cast: [{ name: "Tom Hanks", img: "https://image.tmdb.org/t/p/w185/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg" }, { name: "Robin Wright", img: "https://image.tmdb.org/t/p/w185/y4JXRST9hsxsLOdTzBTkMpDkDyz.jpg" }, { name: "Gary Sinise", img: "https://image.tmdb.org/t/p/w185/pqBn71VoUFdH1dRXKAuaanCNxFH.jpg" }], trailerLink: "https://www.youtube.com/watch?v=bLvqoHBptjg" },
};

// TV Shows — separate IDs so they don't clash with movies
export const TV_SHOWS_DB = {
    "t1": { _id: "t1", title: "Breaking Bad", year: 2008, seasons: 5, genre: ["Thriller", "Drama"], mood: ["Thriller"], rating: 9.5, status: "Ended", description: "A high school chemistry teacher turns to manufacturing methamphetamine after a terminal cancer diagnosis. Widely considered the greatest TV show ever made.", posterUrl: "https://image.tmdb.org/t/p/w780/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", bgUrl: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", posterColor: "linear-gradient(135deg,#1A0808,#D85030)", neon: "#FB923C", cast: [{ name: "Bryan Cranston", img: "https://image.tmdb.org/t/p/w185/7Jahy5LZX2Fo8fGJltMreAI49hC.jpg" }, { name: "Aaron Paul", img: "https://image.tmdb.org/t/p/w185/u6Rb3qPMuiPhGsCnMiEJoTBTxhR.jpg" }, { name: "Anna Gunn", img: "https://image.tmdb.org/t/p/w185/adppyeu95gNiMuxHOOf9VKOoREy.jpg" }], trailerLink: "https://www.youtube.com/watch?v=HhesaQXLuRY" },
    "t2": { _id: "t2", title: "Game of Thrones", year: 2011, seasons: 8, genre: ["Fantasy", "Drama"], mood: ["Thriller", "Emotional"], rating: 9.2, status: "Ended", description: "Nine noble families wage war for control of the mythical land of Westeros. An epic saga of power, betrayal, and dragons.", posterUrl: "https://image.tmdb.org/t/p/w780/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg", bgUrl: "https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg", posterColor: "linear-gradient(135deg,#140A00,#7A5200)", neon: "#F59E0B", cast: [{ name: "Emilia Clarke", img: "https://image.tmdb.org/t/p/w185/yi3bkKYcRRaZrEjnLEsRjXoT7PZ.jpg" }, { name: "Kit Harington", img: "https://image.tmdb.org/t/p/w185/dGk8CsKo1h5G2jTU5VBFHAtEJPk.jpg" }, { name: "Peter Dinklage", img: "https://image.tmdb.org/t/p/w185/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg" }], trailerLink: "https://www.youtube.com/watch?v=gcTkNV7GiEY" },
    "t3": { _id: "t3", title: "Stranger Things", year: 2016, seasons: 4, genre: ["Sci-Fi", "Horror"], mood: ["Thriller", "Sci-Fi"], rating: 8.7, status: "Ongoing", description: "A group of kids in a small town uncover supernatural forces and a secret government experiment that threatens everything they know.", posterUrl: "https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", bgUrl: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg", posterColor: "linear-gradient(135deg,#050A18,#1A5A8A)", neon: "#38BDF8", cast: [{ name: "Millie Bobby Brown", img: "https://image.tmdb.org/t/p/w185/oVGBhH8P6MnJT3Ep6KWO3AwPBs0.jpg" }, { name: "Finn Wolfhard", img: "https://image.tmdb.org/t/p/w185/8ZjnBnFkKkHrqFOHAEBJmBGShMj.jpg" }, { name: "Gaten Matarazzo", img: "https://image.tmdb.org/t/p/w185/mHHTOLuFkNR5VHp2lJuQsEdFnNi.jpg" }], trailerLink: "https://www.youtube.com/watch?v=b9EkMc79ZSU" },
    "t4": { _id: "t4", title: "The Crown", year: 2016, seasons: 6, genre: ["Drama", "Biography"], mood: ["Emotional", "Motivated"], rating: 8.6, status: "Ended", description: "The political rivalries and romances of Queen Elizabeth II's reign, and the events that shaped the second half of the 20th century.", posterUrl: "https://image.tmdb.org/t/p/w780/1M876KPjulVwppEpldhdc8V4o68.jpg", bgUrl: "https://image.tmdb.org/t/p/original/1M876KPjulVwppEpldhdc8V4o68.jpg", posterColor: "linear-gradient(135deg,#0A1428,#3A6A9A)", neon: "#818CF8", cast: [{ name: "Olivia Colman", img: "https://image.tmdb.org/t/p/w185/6i8wHzXSFDlN8tRGHJLPGfZQTdh.jpg" }, { name: "Tobias Menzies", img: "https://image.tmdb.org/t/p/w185/vfYnRIFrVFSPJoKPBxFfxS4SkD0.jpg" }, { name: "Helena Bonham Carter", img: "https://image.tmdb.org/t/p/w185/bHkLnubV8TuDxDmSzO8iFNqlPFX.jpg" }], trailerLink: "https://www.youtube.com/watch?v=JWtnJjn6ng0" },
    "t5": { _id: "t5", title: "Money Heist", year: 2017, seasons: 5, genre: ["Thriller", "Crime"], mood: ["Thriller", "Motivated"], rating: 8.2, status: "Ended", description: "A criminal mastermind who goes by 'The Professor' recruits a band of robbers to carry out the most elaborate heist in history.", posterUrl: "https://image.tmdb.org/t/p/w780/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", bgUrl: "https://image.tmdb.org/t/p/original/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", posterColor: "linear-gradient(135deg,#3A0808,#C83030)", neon: "#EF4444", cast: [{ name: "Álvaro Morte", img: "https://image.tmdb.org/t/p/w185/6I4H2bXM5oLReMtfMkgIRcGkAHe.jpg" }, { name: "Úrsula Corberó", img: "https://image.tmdb.org/t/p/w185/rvHrQ8cKEI3pAiZjdHjGxEK5eRH.jpg" }, { name: "Itziar Ituño", img: "https://image.tmdb.org/t/p/w185/rqYnj7EWlQ9Vv7FQdBzY3NfqKu0.jpg" }], trailerLink: "https://www.youtube.com/watch?v=_lqToJCCCFk" },
    "t6": { _id: "t6", title: "Friends", year: 1994, seasons: 10, genre: ["Comedy", "Romance"], mood: ["Happy", "Romance"], rating: 8.9, status: "Ended", description: "Six friends navigate love, careers, and life in New York City. A timeless comedy that defined a generation of television.", posterUrl: "https://image.tmdb.org/t/p/w780/f496cm9enuEsZkSPzCwnTESEK5s.jpg", bgUrl: "https://image.tmdb.org/t/p/original/f496cm9enuEsZkSPzCwnTESEK5s.jpg", posterColor: "linear-gradient(135deg,#1A2A3A,#4A8AC8)", neon: "#FCD34D", cast: [{ name: "Jennifer Aniston", img: "https://image.tmdb.org/t/p/w185/1GWBs5F4i8dkGeMfMn0jWymBvl3.jpg" }, { name: "Courteney Cox", img: "https://image.tmdb.org/t/p/w185/6k59llUxKKlhkWNhgTPHKNbHRV4.jpg" }, { name: "Lisa Kudrow", img: "https://image.tmdb.org/t/p/w185/h0v5OVIdLR5LQl3K56PLFoIBhHY.jpg" }], trailerLink: "https://www.youtube.com/watch?v=g-xAbsLCBSc" },
    "t7": { _id: "t7", title: "Squid Game", year: 2021, seasons: 2, genre: ["Thriller", "Drama"], mood: ["Thriller"], rating: 8.0, status: "Ongoing", description: "Hundreds of desperate cash-strapped contestants compete in a series of deadly children's games for a chance to win a life-changing prize.", posterUrl: "https://image.tmdb.org/t/p/w780/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", bgUrl: "https://image.tmdb.org/t/p/original/qw3J9cNeLioOLoR68WX7z79aCdK.jpg", posterColor: "linear-gradient(135deg,#0A1A1A,#2A8A6A)", neon: "#34D399", cast: [{ name: "Lee Jung-jae", img: "https://image.tmdb.org/t/p/w185/e0FatnEAKWO6dBVxH6rqiSAJBXu.jpg" }, { name: "Park Hae-soo", img: "https://image.tmdb.org/t/p/w185/gKsOHxAb1jzVh5t8w0J6K6glxNl.jpg" }, { name: "HoYeon Jung", img: "https://image.tmdb.org/t/p/w185/tgzWAJFBCfqjMNg1GxaZJ88PkKC.jpg" }], trailerLink: "https://www.youtube.com/watch?v=oqxAJKy0ii4" },
    "t8": { _id: "t2", title: "The Witcher", year: 2019, seasons: 3, genre: ["Fantasy", "Drama"], mood: ["Thriller", "Motivated"], rating: 8.2, status: "Ongoing", description: "Geralt of Rivia, a mutated monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.", posterUrl: "https://image.tmdb.org/t/p/w780/7vjaCdMw15FEbXyLQTVa04URsPm.jpg", bgUrl: "https://image.tmdb.org/t/p/original/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg", posterColor: "linear-gradient(135deg,#0A1408,#2A5A20)", neon: "#34D399", cast: [{ name: "Henry Cavill", img: "https://image.tmdb.org/t/p/w185/bseULGSfNm7F4lPKVKiMJXXtKCe.jpg" }, { name: "Freya Allan", img: "https://image.tmdb.org/t/p/w185/wasMFuQ0eCpPW6qKdJF8NvJEsaW.jpg" }, { name: "Anya Chalotra", img: "https://image.tmdb.org/t/p/w185/m0eoFJBTf4HrT6fSMCTrEpzXMh0.jpg" }], trailerLink: "https://www.youtube.com/watch?v=ndl7RQ8sHCE" },
    "t9": { _id: "t9", title: "Peaky Blinders", year: 2013, seasons: 6, genre: ["Crime", "Drama"], mood: ["Thriller", "Motivated"], rating: 8.8, status: "Ended", description: "A gangster family epic set in 1919 Birmingham, centered on the Shelby crime family and their ambitious leader Tommy Shelby.", posterUrl: "https://image.tmdb.org/t/p/w780/vUUqzWa2LnHIVqkaKVlVGkPmNlR.jpg", bgUrl: "https://image.tmdb.org/t/p/original/vUUqzWa2LnHIVqkaKVlVGkPmNlR.jpg", posterColor: "linear-gradient(135deg,#0A0808,#4A2A08)", neon: "#F59E0B", cast: [{ name: "Cillian Murphy", img: "https://image.tmdb.org/t/p/w185/dm6V24NjjvjMiCtbMkc8Y2WPm2.jpg" }, { name: "Paul Anderson", img: "https://image.tmdb.org/t/p/w185/rDYDW5PpOaBxh9N0Z7N26Qdp3qg.jpg" }, { name: "Helen McCrory", img: "https://image.tmdb.org/t/p/w185/5i0iFhQqMtN7MlATxSUY2xoVr4g.jpg" }], trailerLink: "https://www.youtube.com/watch?v=oVzVdvGIC7U" },
    "t10": { _id: "t10", title: "The Office", year: 2005, seasons: 9, genre: ["Comedy"], mood: ["Happy", "Chill"], rating: 8.9, status: "Ended", description: "A mockumentary sitcom about the everyday lives of office employees at the Dunder Mifflin Paper Company in Scranton, Pennsylvania.", posterUrl: "https://image.tmdb.org/t/p/w780/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg", bgUrl: "https://image.tmdb.org/t/p/original/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg", posterColor: "linear-gradient(135deg,#1A3A1A,#4A8A4A)", neon: "#34D399", cast: [{ name: "Steve Carell", img: "https://image.tmdb.org/t/p/w185/fM9wJfZqOGGOSKVGzsgrK7E7sYJ.jpg" }, { name: "John Krasinski", img: "https://image.tmdb.org/t/p/w185/oHzPWwmWjDASmKlR5OUcJh2I6i7.jpg" }, { name: "Jenna Fischer", img: "https://image.tmdb.org/t/p/w185/5gmWpyLrBJLxKTyCTJlPAlq3GJG.jpg" }], trailerLink: "https://www.youtube.com/watch?v=LHOtClRjxSw" },
};

export const MOVIES_LIST = Object.values(MOVIES_DB);
export const TV_SHOWS_LIST = Object.values(TV_SHOWS_DB);

// Featured — replaced Dark Knight (#9) and La La Land (#1) with better landscape images
// Using: Oppenheimer, Interstellar, Inception, Parasite, Coco
export const FEATURED = [
    MOVIES_DB["5"],  // Oppenheimer — great landscape bg
    MOVIES_DB["2"],  // Interstellar — perfect space landscape
    MOVIES_DB["8"],  // Inception — great city scenes
    MOVIES_DB["11"], // Parasite — good wide shots
    MOVIES_DB["10"], // Coco — colorful landscape
];

export const TRENDING = [
    { ...MOVIES_DB["9"], tag: "HOT" },
    { ...MOVIES_DB["4"], tag: "HOT" },
    { ...MOVIES_DB["5"], tag: "POPULAR" },
    { ...MOVIES_DB["8"], tag: "POPULAR" },
    { ...MOVIES_DB["3"], tag: "CLASSIC" },
    { ...MOVIES_DB["11"], tag: "CLASSIC" },
];

// Combined DB for MovieDetail — works for both movies and TV shows
export const ALL_CONTENT_DB = { ...MOVIES_DB, ...TV_SHOWS_DB };